# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: $(build.sourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: sed -i 's/#BUILD_ID#/$(build.buildNumber)/g' _includes/header.html
  displayName: 'update site with build number'

- script: docker build -f Dockerfile -t workshop --target build .
  displayName: 'docker build'
  
- script:  |
  id=$(docker create workshop)
  docker cp $id:/src/app/_site $(Build.ArtifactStagingDirectory)
  displayName: 'Copy published files'

- task: PublishBuildArtifacts@1